### ISSUE TITLE
vivado 2018.2 release: could not find module 'ila_sfen_rxclk' 

### ISSUE THREAD

**Issue by flynneva** [Digilent/Zybo-Z7-20-pcam-5c#12]
Following the README as well as adding the repo/vivado_library/ folder to my IP sources I am still getting this error when opening the .xdc project file from the release.

> [Designutils 20-1280] Could not find module 'ila_sfen_rxclk'. The XDC file d:/repos/Zybo-Z7-20-pcam-5c/proj/Zybo-Z7-20-pcam-5c.srcs/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/ila_v6_2/constraints/ila.xdc will not be read for any cell of this module.

Any ideas on how to fix this?

**Comment by flynneva** [comment]
I think I may have figured it out...currently following these directions from the [" Workflows 1. Cloning a Repo that uses this Subodule"](https://github.com/Digilent/digilent-vivado-scripts)

**Comment by flynneva** [comment]
see #10 for some help....I followed his advice and got it working.

**Comment by gzzyyxh** [comment]
@flynneva  Hi, I'm experiencing the same issue. Could you share some suggestions?
