### ISSUE TITLE
compile error: XPAR_DDYNCLK_NUM_INSTANCES is not declared

### ISSUE THREAD

**Issue by modmod24** [Digilent/Zybo-Z7-20-pcam-5c#3]
There is some issue with the **axi_dynclk_v1_1** hw driver. In SDK in the board support package I had to change 

`/*
* The configuration table for devices
*/

DDynClk_Config DDynClk_ConfigTable[**XPAR_DDYNCLK_NUM_INSTANCES**] =
{
   {
      XPAR_VIDEO_DYNCLK_DEVICE_ID,
      XPAR_VIDEO_DYNCLK_S_AXI_LITE_BASEADDR
   }
};`

into 

`/*
* The configuration table for devices
*/

DDynClk_Config DDynClk_ConfigTable[**XPAR_AXI_DYNCLK_NUM_INSTANCES**] =
{
   {
      XPAR_VIDEO_DYNCLK_DEVICE_ID,
      XPAR_VIDEO_DYNCLK_S_AXI_LITE_BASEADDR
   }
};
`
as XPAR_DDYNCLK_NUM_INSTANCES is not defined in xparameters.h

**Comment by elodg** [comment]
@modmod24 I pushed some changed to replace dynclk completely, which should fix this issue. Please verify.
