### ISSUE TITLE
SW: compilation error «Type 'retry_count_' was not declared in this scope»

### ISSUE THREAD

**Issue by modmod24** [Digilent/Zybo-Z7-20-pcam-5c#4]
https://github.com/Digilent/Zybo-Z7-20-pcam-5c/blob/e2dac9736661801065d741eb4a84ca3321507ebf/sdk/pcam_vdma_hdmi/src/ov5640/OV5640.h#L628-L630

I just downloaded the git master branch as zip and imported in SDK. Some compile errors appear during build.

**Comment by modmod24** [comment]
I think I don't have my project setup for CPP.

**Comment by modmod24** [comment]
yes, after following this guide: https://reference.digilentinc.com/learn/programmable-logic/tutorials/github-demos/start 
application project is set up for C. I created an empty CPP application and imported sources.

**Comment by elodg** [comment]
Could not reproduce. Importing existing projects should not change application language type.
