### ISSUE TITLE
terminate called after throwing an instance of 'digilent::OV5640::HardwareError'

### ISSUE THREAD

**Issue by fonzg1** [Digilent/Zybo-Z7-20-pcam-5c#5]
Can any one help me understand what this error message means?
here is my situation:
I been trying to build the pcam-5c project for the zybo-z7 system but i have had no success with it..
I'm using a Rasp-pi cam instead of the mipi Pcam-5c, do I actually need to use the Pcam-5c?

**Comment by modmod24** [comment]
zybo is pin compatible with your picam so yes you can use it you just have you write the driver for your module. there are different picams so you will need to know which one you have. 

the error message means that the board had not been recognized by the driver software

**Comment by elodg** [comment]
Looking at the source code, this exception is thrown when there is a hardware error during the initialization of the OV5640 sensor: https://github.com/Digilent/Zybo-Z7-20-pcam-5c/blob/master/sdk/pcam_vdma_hdmi/src/ov5640/OV5640.h#L529

This demo was written for the Zybo Z7 and the Pcam 5C. It will not work with other sensor without modification. Not a bug.
