### ISSUE TITLE
vivado 2018.2

### ISSUE THREAD

**Issue by bobwmcgrath** [Digilent/Zybo-Z7-20-pcam-5c#7]
I know this pcam demo was made for vivado 2017.4 and I was able to get that working with that version.  Seeing as vivado takes up a bunch of storage space however, I would like to get this to work with 2018.2.  The issue seems be "IP definition 'MIPI_D_PHY_RX (1.2)' for IP 'system_MIPI_D_PHY_RX_0_0' (customized with software release 2017.4) was not found in the IP Catalog." and "IP definition 'MIPI_CSI_2_RX (1.1)' for IP 'system_MIPI_CSI_2_RX_0_0' (customized with software release 2017.4) was not found in the IP Catalog."  Even though it looks like I do have the IP in my catalogue, my guess is that the IP I have is a newer version.  Any thoughts or suggestions on howto solve this would be appreciated.  Thanks.

**Comment by elodg** [comment]
The IPs mentioned are included on a branch of the vivado-library submodule. When cloning the project, use --recursive to clone submodules too. Or, after cloning non-recursively, do submodule init, submodule update.
Confirm that the IP folders are checked out in repo/vivado-library/ip

**Comment by bobwmcgrath** [comment]
I recursively cloned the vivado-library repo, and the did "add repository" in vivado.  This added 56 ips, but none of the are the mipi ips that I am looking for.  Any ideas what I'm doing wrong?

**Comment by elodg** [comment]
I just checked out the master branch recursively and re-created the project in Vivado 2017.4.
![image](https://user-images.githubusercontent.com/7438625/45764248-f9362380-bc3a-11e8-9013-2f97c988ab0b.png)

**Comment by bobwmcgrath** [comment]
ah ha.  you meant I should clone the project not the library.  every thing looks good now.  thanks a bunch
