### ISSUE TITLE
PCam 5 Vivado 2018.2 

### ISSUE THREAD

**Issue by estibalitz** [Digilent/Zybo-Z7-20-pcam-5c#8]
I have tried your code but I do get two error, just afterdoing:
.import--> File System-->sdk_appsrc/pcam_vdma_hdmi
that are:

![error](https://user-images.githubusercontent.com/23641375/54212207-e19d7080-44e2-11e9-90de-8c30d129d7de.PNG)

and I dont understand what can be wrong

**Comment by elodg** [comment]
Make sure pcam_vdma_hdmi is a C++ project when creating.

**Comment by estibalitz** [comment]
And the other one? Because it is defined to be an empty application proyect

**Comment by estibalitz** [comment]
The programs closes as soon as pcam_vdma_hdmi is defined as a C++ project. It only enables Target Software Language to C. After defining the blanck empty application in C,  there are  no issues or errors. 
![imagen](https://user-images.githubusercontent.com/23641375/54260339-edcc1100-4568-11e9-9be3-55d25bbc5991.png)

But the main error comes when including the import files
![imagen](https://user-images.githubusercontent.com/23641375/54260437-2f5cbc00-4569-11e9-9a6c-cbf641b7defb.png)

where some fo them are not defined as:
1. the main
2. make. ***[pcam_vdma_hdmi.elf]

![imagen](https://user-images.githubusercontent.com/23641375/54260562-8b274500-4569-11e9-9bbb-b4cc8e71b37b.png)

**Comment by elodg** [comment]
Ignore the importing/creating FSBL for now, you might not even need it. 
The error message you must focus on is: "undefined reference to 'main'". This is linker error saying that when linking all the libraries/modules together your C/C++ application does not have a main function present.
If you created pcam_vdma_hdmi as a C++ application and you imported main.cc correctly, it will have a main function defined.

**Comment by estibalitz** [comment]
you were right, I did add them and there was no longer error regarding to the "undefined reference to 'main'". But an warning promps up because of ps7_cortexa_9. 
![imagen](https://user-images.githubusercontent.com/23641375/54270206-2d055c80-457f-11e9-9c34-e67afb9203e8.png)
I have looked to some forums, and it ios supossed to be something about the drivers, but adding -g-O0 doesn´t work for me as it was supossed ( i get 98 errors)
![imagen](https://user-images.githubusercontent.com/23641375/54270430-b1f07600-457f-11e9-9077-806cf93ff680.png)

**Comment by elodg** [comment]
Re-create the launch configurations, or better yet the whole workspace.
